### ISSUE TITLE
Please test the syntax of route.data and tp.data

### ISSUE THREAD

**Issue by Desgard** [HackSwjtu/HackRunningGo#1]
Send a response to test the syntax of `route.data` and `tp.data`.
These two files are our data source.
Please pay attention.

**Comment by EldestBard** [comment]
there's no point data in tp.data after running updateRoutes.py

**Comment by Desgard** [comment]
@EldestBard 
There are something changed! You can write your personal account to `users.data`, and then run `updateRoutes.py`. 
The updating data script has been changed by personal account. And we will change the `README.md`. You can find these features in this [pull request](https://github.com/HackSwjtu/HackRunningGo-SC/commit/659e14cab65825d928bd84c88221401523173e6e)
