### ISSUE TITLE
Problems after running 

### ISSUE THREAD

**Issue by Augn** [HackSwjtu/HackRunningGo#11]
Error occurred after the operation, did not show the running route, and should be 1 green and 4 Blue points, only 4 blue point now, and now run after landing the flash back phenomenon, the authors hope to see this message.

**Comment by HandsomeHow** [comment]
It doesn't matter at all! Any how, there is no such a checker to check whether the route is valid.
It only matters whether the total distance of your account increase or not.

**Comment by Augn** [comment]
Obsessive compulsive disorder, did not show the map is not good.
