### ISSUE TITLE
Now can not be used, the server has banned the old version, and now the latest version is 1.3.1 

### ISSUE THREAD

**Issue by Augn** [HackSwjtu/HackRunningGo#13]
Now can not be used, the server has banned the old version, and now the latest version is 1.3.1

**Comment by Mud-Player** [comment]
trust me, the author will update it!

**Comment by Augn** [comment]
Can only believe the author, 25 on the end of the run.

**Comment by lianglanzheng** [comment]
The new version iydsj added IMEI, MAC Adress, Channel, Device Model & Signature to network packets.
You could fix it and send a pull request to us.

**Comment by EldestBard** [comment]
it's login post address has been changed into api/v5/login
