### ISSUE TITLE
please tell me if the author will updata?

### ISSUE THREAD

**Issue by Mud-Player** [HackSwjtu/HackRunningGo#14]
or i hava to run by legs, because there isn't enough times.
thanks.

**Comment by realJustinLee** [comment]
上海大学来签到，我们也要用这个软件啦，正在尝试解决上述问题（不知道要搞到什么时候）-_-#

**Comment by Augn** [comment]
The author is dealing with.

**Comment by Mud-Player** [comment]
@Augn you are very good......hhhhhhhh

**Comment by Desgard** [comment]
@ftz8137 会更，但是现在在搞毕设。时间不多，你要有兴趣也可以研究一下。

**Comment by Desgard** [comment]
@Great-Li-Xin 欢迎一起讨论哈。😄

**Comment by realJustinLee** [comment]
@Desgard     吼啊,吼啊，都钦定了，我肿么能拒绝呢^_^

**Comment by Mud-Player** [comment]
@Desgard 没学过python，暂时没时间学python

**Comment by Desgard** [comment]
@ftz8137 在另外一个repo中提供了全套接口，但是现在的数据返回和sample有所差异，你可以用自己熟悉的语言来写。

**Comment by Mud-Player** [comment]
@Desgard c++都还没学完，网络编程正在自学，可是还有两周跑步结束。。。。

**Comment by Augn** [comment]
And updated 1.3.2
The data is encrypted again
Repair bug

**Comment by lianglanzheng** [comment]
This repositorie will not be update.
You can contribute your ideas to the rust version of HRG [HackSwjtu/running-go-rs](https://github.com/HackSwjtu/running-go-rs).
