### ISSUE TITLE
目前更新1.3.6 失效了

### ISSUE THREAD

**Issue by 1368129224** [HackSwjtu/HackRunningGo#17]
增加了步频什么的，希望大佬更一下，万分感谢！！

**Comment by lianglanzheng** [comment]
已转告大佬，不过还是希望大家有空多出去跑步

**Comment by ly1102** [comment]
多了一个tokensign验证，每一次抓包看到的这个sign值都不一样，应该是根据时间戳来生成的，但是用了主流的生成token值的办法来测试过得不到上传时候的那个tokensign。然后我尝试了反编译app，发现他的代码里面并没有涉及到任何的http模块，不知道这个他是怎么实现的

**Comment by Desgard** [comment]
@ly1102
有兴趣的话可以和我们团队一起研究

**Comment by ly1102** [comment]
@Desgard 
我对信安这方面了解比较少，我一般做的是开发的事情。0.0，最近就是觉得跑步这个太不人道，就想逆向一下，后来发现是经过了360加固的，这个难度太大了。

**Comment by BetaMee** [comment]
突然发现还有这个组织呀，请问可以参与这个项目吗？

**Comment by Desgard** [comment]
@BetaMee
如果参与项目的话直接发起issue或者 pull request就好。如果加入组织请参看这个链接。

**Comment by Desgard** [comment]
@BetaMee
http://www.hackswjtu.com/I-want-you/
