### ISSUE TITLE
运动世界会检测安卓模拟器从而无法使用GPS定位

### ISSUE THREAD

**Issue by Evilmass** [HackSwjtu/HackRunningGo#18]
能不能从这个方向入手，排除这些检测？尝试过反编译，但代码是加固过的，无法看到真正的程序逻辑。

**Comment by Desgard** [comment]
不瞒您说，我之前尝试过iOS端的逆向。在对于方法的hook步骤失败。我怀疑其项目中使用Swift实现（或是Swift桥接ObjC）。class-dump工具在获取其方法列表的时候以失败告终。至于安卓方面，小组成员@Andy971115 正在研究。

其实这个软件也不牵涉到自己的利益问题，所以我自己也就不太关注了。(╯‵□′)╯︵┻━┻

**Comment by violarulan** [comment]
@Evilmass @Desgard 

对 360 加固的逆向略有研究，自己提取出了完整的 classes.dex 文件，不过类名/函数名等略有混淆

![shot.jpg](https://i.loli.net/2017/08/27/59a2765e2d434.jpg)

[classes.dex_8176364.zip](https://github.com/HackSwjtu/HackRunningGo-SC/files/1254197/classes.dex_8176364.zip)

**Comment by WangHexie** [comment]
@violarulan 你提取的这个是什么版本的版本号多少？

**Comment by violarulan** [comment]
@WangHexie 1.4.5

1.4.5 目前仍为可用版本（上传使用 v14 API）
