### ISSUE TITLE
Windows 系环境下,控制台输出乱码

### ISSUE THREAD

**Issue by suica** [HackSwjtu/HackRunningGo#23]
![](http://i4.buimg.com/519918/7c0fb8e6651ede8a.png)

这是updateRoutes.py的部分运行输出.

windows下,git bash, cmd, powershell都默认采用gbk (gb2312)编码. 

python默认用utf-8编码输出,会产生中文乱码.

**Comment by ankanch** [comment]
将`控制台的代码页修改为UTF-8`即可。
使用以下命令：
```shell
chcp 65001
 ```
