### ISSUE TITLE
每次跑的公里数是哪个值

### ISSUE THREAD

**Issue by kosmosr** [HackSwjtu/HackRunningGo#24]
有的时候会跑1.98公里 没有完成目标(2公里) 想看看是哪个值决定的。。

**Comment by kosmosr** [comment]
每次跑的完成时间跟真实时间差几十分钟。。。

**Comment by beihaiguaishou** [comment]
每次运行的时间，是作为结束时间，不是开始时间。记录是根据约炮记录生成的。
