### ISSUE TITLE
我被查到了 老哥 

### ISSUE THREAD

**Issue by kosmosr** [HackSwjtu/HackRunningGo#28]
= =

**Comment by ly1102** [comment]
没有做什么过分的事情吧？

**Comment by kosmosr** [comment]
@ly1102 没有噢 就帮我室友跑了下、。

**Comment by Desgard** [comment]
我估计他们是对应 IP 和 设备号的。你同一个IP、同一个设备两个账号太容易被发现了。。

**Comment by ly1102** [comment]
那我一个人跑了十几个账号岂不是很尴尬。。。

**Comment by kosmosr** [comment]
大意了 确实是设备号的问题

**Comment by Desgard** [comment]
@ly1102 非常尴尬。建议你换号刷的时候，自己挂着vpn或者云服务器来搞。

**Comment by ly1102** [comment]
手机版不能@人呢。。。
我之前以为手机信息编码了不能破译，就这么用了。。。不过IP的话，用学校的问题应该不大，用学校IP上传信息很正常，大家都在用学校的网嘛。用服务器也是同一个IP这个就更容易被查到吧

**Comment by kosmosr** [comment]
@ly1102 应该不会 我帮一个外地的人刷了 也没事 就我这学校翻车了 估计是不是有人举报

**Comment by ly1102** [comment]
学校老师说这个数据最后会交给学校，好像最后进行处理的是学校，所以有可能是这样。我们学校的这周末才结束。之前我想改一下每次跑步的总时间和距离，但是没有找到😂，就只改了跑步开始的时间和登录用户，加到了一个setting文件，这样跑步就方便多了
