### ISSUE TITLE
话说你们的有没有被清 今天

### ISSUE THREAD

**Issue by kosmosr** [HackSwjtu/HackRunningGo#30]

**Comment by ly1102** [comment]
我刷的全都没有了。。。可能是因为跑步的距离和时间，步频完全都一样吧，我一直没有找到怎么更改距离步频的办法。。。

**Comment by kosmosr** [comment]
@ly1102 应该是这个APP更新了的缘故 我用他们手机信息跑的都没了 步频也是不同的啊

**Comment by ly1102** [comment]
也就是说只能有一个设备跑过步了哦？

**Comment by kosmosr** [comment]
@ly1102 应该不是设备的问题了 这个代码估计被官方针对了。。。用模拟器就没事

**Comment by ly1102** [comment]
那这就很尴尬了QAQ，我的那么多公里全没了

**Comment by EldestBard** [comment]
大家的代码是不是没有修改http请求的user-agent

**Comment by ly1102** [comment]
我没改。。。

**Comment by EldestBard** [comment]
那有可能是官方通过检测这个批量删除的记录

**Comment by EldestBard** [comment]
我刚才抓包的时候看到endtime是6月5号23:59:59，这个软件也是够精的

**Comment by Tommy9743** [comment]
求大佬更新啊  翻水水了哟

**Comment by ankanch** [comment]
话说他是多久清空的数据？不知道老师记录成绩没？

**Comment by Tommy9743** [comment]
@ankanch 是啊  我这边还没结算成绩呢  啊啊啊啊啊啊啊啊啊  翻车 好难受

**Comment by EldestBard** [comment]
有可能是服务器上有人通过记录上特征筛选出来的

**Comment by Desgard** [comment]
邮件响了一早上。。真是醉了。。

**Comment by ly1102** [comment]
那就搞个QQ群啥的吧，大家也方便交流和搞程序

**Comment by ankanch** [comment]
@EldestBard   endtime 是6.5 23.59.59 是什么意思？成绩统计的截止日期？


按理说，老师今天不上班吧，要到周一才登成绩。
不知道这个是多久被清空的？

**Comment by EldestBard** [comment]
@ankanch 抓包的时候服务器上返回的，有一个starttime和一个endtime，应该是过了这个时间再跑的话就不计入这学期了吧。

**Comment by ankanch** [comment]
卧槽，我刚刚又刷了一次。。。90公里又跑完了啊。。。现在主要看体育老师记录成绩了。


-- 

Best regards,


Kanch ＠ Chengdu University of Information Technology

2015 Computer Science Major


Mail:kanchisme@gmail.com

No.24 Block 1, Xuefu Road, Chengdu, Sichuan, China


Send from my Nexus6P

**Comment by suica** [comment]
用这个程序上传的成绩被清空的，是不是都曾经在同一台电脑上登过两个及以上帐号呢？

**Comment by Tommy9743** [comment]
我是登了2个号

**Comment by ankanch** [comment]
我也是


-- 

Best regards,


Kanch ＠ Chengdu University of Information Technology

2015 Computer Science Major


Mail:kanchisme@gmail.com

No.24 Block 1, Xuefu Road, Chengdu, Sichuan, China


Send from my Nexus6P

**Comment by become2019** [comment]
我没有登录两个号。。。。照样被清
