### ISSUE TITLE
现用 API 已失效

### ISSUE THREAD

**Issue by violarulan** [HackSwjtu/HackRunningGo#33]
```text
upload response: {"timestamp":1504401770345,"status":404,"error":"Not Found","message":"No message available","path":"/api/v10/runnings/add_record"}
```

2017/11/30 更新 1.5.0，脱壳出 3 个 classes.dex

![c2so8zx1b _ hvj0t 9qkbu](https://user-images.githubusercontent.com/10095657/33413301-c11dca94-d5cb-11e7-8ec1-81140a2aad57.png)

[zjwh_1.5.0_classes.dex.tar.gz](https://github.com/HackSwjtu/HackRunningGo/files/1516552/zjwh_1.5.0_classes.dex.tar.gz)

<hr />

目前应该是更新了 API，我成功 dump 出了 classes.dex 文件，贡献出来希望大家一起分析源码

[classes.dex_8176364.zip](https://github.com/HackSwjtu/HackRunningGo-SC/files/1272658/classes.dex_8176364.zip)

**Comment by Desgard** [comment]
可以，我开个这个项目的群聊，大家可以一块讨论下。由于我现在没有再维护这个项目了，希望社区其他小伙伴能 contribution 😁

**Comment by wrl96** [comment]
看了一下 就是把uid token timestamp拼到了一起 但是做md5加密前还加了盐 这个盐应该在strings.xml里 楼主能提供一下么

**Comment by wrl96** [comment]
找到了两个salt md5_sign_salt=&wh2016_swcampus md5_sign_salt_run=&ODJw#h03b_0EaV 然而按照反编译出来的代码算出来的md5不正确

**Comment by WangHexie** [comment]
360加固的时候是否xml也有加固？似乎代码里有getstring()方法但是XML里没有找到相应字符串。dump出的过程从其他文件是否也有变化？

**Comment by WangHexie** [comment]
就差这一个字符串signature就出来了

**Comment by violarulan** [comment]
@WangHexie 似乎是储存在本地的 `sports.db` ?

**Comment by waveyan** [comment]
@WangHexie @violarulan  signature怎么弄得
