### ISSUE TITLE
哈哈

### ISSUE THREAD

**Issue by beginner123L** [HackSwjtu/HackRunningGo#36]

**Comment by fghzxm** [comment]
Did you just successfully cracked 1.4.9 or ...?

**Comment by beginner123L** [comment]
I am just a beginner,,,and my English is poor,could you help me?

**Comment by fghzxm** [comment]
那看来是我想多了。。。（汗

**Comment by beginner123L** [comment]
我的天，莫名想笑
加个QQ呗

**Comment by fghzxm** [comment]
免
另：觉得还是关了这个 issue 重开一个吧，要不成了聊天了

**Comment by beginner123L** [comment]
我啥都不知道，就只是想刷个跑步路程，奈何，哎
