### ISSUE TITLE
 No module named requests

### ISSUE THREAD

**Issue by wantRP** [HackSwjtu/HackRunningGo#38]
安了requests库了
然后pip install HackRunningGo-SC,No matching distribution found for HackRunningGo-SC

**Comment by violarulan** [comment]
你是不是弄错了什么
```
pip install requests
git clone https://github.com/HackSwjtu/HackRunningGo
cd HackRunningGo
...
```

**Comment by wantRP** [comment]
现在弄好了装上了，但是又说UnicodeEncodeError: 'ascii' codec can't encode characters in position 42-43: ordinal not in range(128)，我已经用notepad++把user.data转成了UTF-8、Windows格式

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by violarulan** [comment]
@zhaobean
Use python 3.6+
