### ISSUE TITLE
请问一下这个是什么出问题了？

### ISSUE THREAD

**Issue by zimoua** [HackSwjtu/HackRunningGo#39]
File "updateRoutes.py", line 231
    print 'got one record for iphone,ignore it'
                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'got one record for iphone,ignore it')?
PS F:\HackRunningGo-feature\HackRunningGo-feature>

**Comment by lianglanzheng** [comment]
This file was written in python 2, print method without brackets is illegal in python 3.
***MORE IMPORTANT: This crack is out of date. Don't run it if you are not a developer.***
