### ISSUE TITLE
running updateRoutes.py issue

### ISSUE THREAD

**Issue by kosmosr** [HackSwjtu/HackRunningGo#8]
python updateRoutes.py 
不能正常运行 如下
Updating 1 running groups data. 
{"fivePointJson":"[]","useZip":false}

**Comment by beihaiguaishou** [comment]
@kosmosr This May cause by none of the path points pass the testpoints,so the fivepoint is null.It's not a big problem if not all record's fivepoints is null.If you are from another school,try replace testpoints' with your school geo coordinate.
