### ISSUE TITLE
Running routes can not be found on the Android platform, IOS can check to.

### ISSUE THREAD

**Issue by Mud-Player** [HackSwjtu/HackRunningGo#9]
maybe some data In the running diary of the line, the data format may not be able to read the correct Android, and IOS can be. I  have no ability to modify the bug ,so i would be appreciate if you can check it.

**Comment by beihaiguaishou** [comment]
@ftz8137 This may cause by path error or fivepoint error,in general，this should hanpen randomly.Just try more times and see whether it work.

**Comment by Mud-Player** [comment]
@ZhouChaofan I have tried many times, maybe my enviroment did not setting correct.
First I execute updateRoutes.py and HaRunGo.py , it was wrong with no request, so I searched for some documents to configure the request but I don't know if I did right.

**Comment by beihaiguaishou** [comment]
@ftz8137 give me some console output.

**Comment by ftz8137** [comment]
@ZhouChaofan here 
['17721879665 546057']
17721879665 546057
Start : Tue Nov 22 10:06:06 2016
{"error":10000,"message":"成功","data":null}
{"error":10000,"message":"成功","data":{"uid":136914,"username":"17721879665","name":"罗林","unid":1001,"nick":"","sex":1,"icon":null,"campusId":"201531060133","depart":"计算机科学学院","registed":true,"role":1,"psign":""}}
Use 24 data
5.30
2.92
{"error":10000,"message":"成功","data":null}
{"error":10000,"message":"成功","data":null}
Sleep 23 seconds

**Comment by ftz8137** [comment]
@ZhouChaofan
['17721879665 546057']
xxxxxxxxxxx 546057
Start : Tue Nov 22 10:06:06 2016
{"error":10000,"message":"成功","data":null}
{"error":10000,"message":"成功","data":{"uid":136914,"username":"xxxxxxxxxx","name":"罗林","unid":1001,"nick":"","sex":1,"icon":null,"campusId":"20153xxxxxxxxxx","depart":"计算机科学学院","registed":true,"role":1,"psign":""}}
Use 24 data
5.30
2.92
{"error":10000,"message":"成功","data":null}
{"error":10000,"message":"成功","data":null}
Sleep 23 seconds

**Comment by Mud-Player** [comment]
@ZhouChaofan
['xxxxxxxxxxxxxx 546057']
xxxxxxxxxxx 546057
Start : Tue Nov 22 10:06:06 2016
{"error":10000,"message":"成功","data":null}
{"error":10000,"message":"成功","data":{"uid":136914,"username":"xxxxxxxxxx","name":"罗林","unid":1001,"nick":"","sex":1,"icon":null,"campusId":"20153xxxxxxxxxx","depart":"计算机科学学院","registed":true,"role":1,"psign":""}}
Use 24 data
5.30
2.92
{"error":10000,"message":"成功","data":null}
{"error":10000,"message":"成功","data":null}
Sleep 23 seconds

**Comment by Mud-Player** [comment]
@ZhouChaofan thank you very much
['xxxxxxxxxxxxxxxx 970311']
{"error":10000,"message":"成功","data":[{"uid":23316,"unid":1001,"name":"朱新宇","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":904,"locLon":104.195026,"locLan":30.837523,"locDesc":"学生公寓21栋","roomId":122083,"beginTime":"2016-11-21 22:34:34","endTime":"2016-11-21 22:51:26","totalNum":2,"currNum":1,"distance":2.0,"currUserEnter":false},{"uid":22221,"unid":1001,"name":"龙绍清","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":122072,"beginTime":"2016-11-21 22:28:57","endTime":"2016-11-21 22:46:24","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":50574,"unid":1001,"name":"于世龙","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":904,"locLon":104.195026,"locLan":30.837523,"locDesc":"学生公寓21栋","roomId":121980,"beginTime":"2016-11-21 21:53:42","endTime":"2016-11-21 22:39:18","totalNum":2,"currNum":1,"distance":2.0,"currUserEnter":false},{"uid":78014,"unid":1001,"name":"成研","icon":"http://imgs.gxapp.iydsj.com/imgs/25da4f6e-e208-48ce-b5ca-545cbb2fc308.jpg","sex":1,"locPid":911,"locLon":104.193822,"locLan":30.83369,"locDesc":"学生公寓19栋","roomId":122061,"beginTime":"2016-11-21 22:22:03","endTime":"2016-11-21 22:39:11","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":68854,"unid":1001,"name":"漆琪","icon":"http://imgs.gxapp.iydsj.com/imgs/7bdc8c6a-67d4-4e7f-8490-e196b7aeb275.jpg","sex":0,"locPid":914,"locLon":104.191639,"locLan":30.830565,"locDesc":"体育馆","roomId":122005,"beginTime":"2016-11-21 22:00:34","endTime":"2016-11-21 22:30:50","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":68607,"unid":1001,"name":"王航","icon":"http://imgs.gxapp.iydsj.com/imgs/1a228666-589d-444b-b979-9aeecab00035.jpg","sex":1,"locPid":916,"locLon":104.191109,"locLan":30.82872,"locDesc":"博学楼","roomId":122029,"beginTime":"2016-11-21 22:10:51","endTime":"2016-11-21 22:27:02","totalNum":2,"currNum":1,"distance":2.0,"currUserEnter":false},{"uid":151720,"unid":1001,"name":"李瑜","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":122042,"beginTime":"2016-11-21 22:13:35","endTime":"2016-11-21 22:26:11","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":18044,"unid":1001,"name":"张朝涵","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":122007,"beginTime":"2016-11-21 22:01:43","endTime":"2016-11-21 22:14:08","totalNum":2,"currNum":1,"distance":2.0,"currUserEnter":false},{"uid":23997,"unid":1001,"name":"刘凤柯","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121960,"beginTime":"2016-11-21 21:47:41","endTime":"2016-11-21 22:06:43","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":17946,"unid":1001,"name":"马欢","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":0,"locPid":906,"locLon":104.192861,"locLan":30.836155,"locDesc":"飞翔路中段","roomId":121880,"beginTime":"2016-11-21 21:33:12","endTime":"2016-11-21 22:05:59","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":119752,"unid":1001,"name":"王绪涛","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":904,"locLon":104.195026,"locLan":30.837523,"locDesc":"学生公寓21栋","roomId":121964,"beginTime":"2016-11-21 21:49:09","endTime":"2016-11-21 22:05:49","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":29781,"unid":1001,"name":"邹浩东","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121972,"beginTime":"2016-11-21 21:51:54","endTime":"2016-11-21 22:05:08","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":130118,"unid":1001,"name":"赵文静","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":911,"locLon":104.193822,"locLan":30.83369,"locDesc":"学生公寓19栋","roomId":121949,"beginTime":"2016-11-21 21:42:38","endTime":"2016-11-21 21:56:59","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":89142,"unid":1001,"name":"朱秋霖","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121930,"beginTime":"2016-11-21 21:39:43","endTime":"2016-11-21 21:54:01","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":17042,"unid":1001,"name":"商洁","icon":"http://imgs.gxapp.iydsj.com/imgs/f496fbbc-2189-4521-b953-e73f59c38094.jpeg","sex":1,"locPid":904,"locLon":104.195026,"locLan":30.837523,"locDesc":"学生公寓21栋","roomId":121801,"beginTime":"2016-11-21 21:23:58","endTime":"2016-11-21 21:51:51","totalNum":4,"currNum":3,"distance":3.0,"currUserEnter":false},{"uid":50653,"unid":1001,"name":"罗健侨","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121891,"beginTime":"2016-11-21 21:34:36","endTime":"2016-11-21 21:49:37","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":20013,"unid":1001,"name":"周严","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121846,"beginTime":"2016-11-21 21:28:40","endTime":"2016-11-21 21:49:23","totalNum":2,"currNum":1,"distance":2.0,"currUserEnter":false},{"uid":27360,"unid":1001,"name":"田文瑞","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121899,"beginTime":"2016-11-21 21:35:31","endTime":"2016-11-21 21:48:55","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":18548,"unid":1001,"name":"彭晓凤","icon":"http://imgs.gxapp.iydsj.com/imgs/e8a54f17-72bd-4a72-abfa-c1ee325676d1.jpg","sex":0,"locPid":916,"locLon":104.191109,"locLan":30.82872,"locDesc":"博学楼","roomId":121769,"beginTime":"2016-11-21 21:20:59","endTime":"2016-11-21 21:34:05","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":22999,"unid":1001,"name":"梁珠","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121692,"beginTime":"2016-11-21 21:15:14","endTime":"2016-11-21 21:30:03","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":20267,"unid":1001,"name":"陈峰","icon":"http://imgs.gxapp.iydsj.com/imgs/63fae6c3-79c5-4aac-a6ea-95eda721cc07.jpg","sex":1,"locPid":914,"locLon":104.191639,"locLan":30.830565,"locDesc":"体育馆","roomId":121162,"beginTime":"2016-11-21 20:16:57","endTime":"2016-11-21 21:26:34","totalNum":4,"currNum":3,"distance":5.0,"currUserEnter":false},{"uid":17923,"unid":1001,"name":"王凯巍","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121464,"beginTime":"2016-11-21 20:52:17","endTime":"2016-11-21 21:20:58","totalNum":2,"currNum":2,"distance":3.0,"currUserEnter":false},{"uid":36233,"unid":1001,"name":"王小波","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":911,"locLon":104.193822,"locLan":30.83369,"locDesc":"学生公寓19栋","roomId":121583,"beginTime":"2016-11-21 21:04:40","endTime":"2016-11-21 21:19:53","totalNum":6,"currNum":5,"distance":2.0,"currUserEnter":false},{"uid":32133,"unid":1001,"name":"徐荣鹏","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121636,"beginTime":"2016-11-21 21:09:51","endTime":"2016-11-21 21:19:14","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":33499,"unid":1001,"name":"唐振宇","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":918,"locLon":104.189021,"locLan":30.828251,"locDesc":"教工食堂","roomId":121514,"beginTime":"2016-11-21 20:58:06","endTime":"2016-11-21 21:18:27","totalNum":2,"currNum":1,"distance":2.0,"currUserEnter":false},{"uid":38709,"unid":1001,"name":"陈天翔","icon":"http://imgs.gxapp.iydsj.com/imgs/4ead5d84-5353-41f8-95be-6122f6a06ad4.jpg","sex":1,"locPid":904,"locLon":104.195026,"locLan":30.837523,"locDesc":"学生公寓21栋","roomId":121446,"beginTime":"2016-11-21 20:50:51","endTime":"2016-11-21 21:18:13","totalNum":2,"currNum":1,"distance":2.0,"currUserEnter":false},{"uid":19569,"unid":1001,"name":"赵胜男","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":917,"locLon":104.188863,"locLan":30.829399,"locDesc":"图书馆","roomId":121608,"beginTime":"2016-11-21 21:07:02","endTime":"2016-11-21 21:18:03","totalNum":2,"currNum":1,"distance":2.0,"currUserEnter":false},{"uid":20591,"unid":1001,"name":"胡宇扬","icon":"http://imgs.gxapp.iydsj.com/imgs/6ab281e6-b78e-48bd-bde5-305f214fd78f.jpg","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121533,"beginTime":"2016-11-21 20:59:44","endTime":"2016-11-21 21:12:27","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":25839,"unid":1001,"name":"张开翔","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121466,"beginTime":"2016-11-21 20:52:37","endTime":"2016-11-21 21:10:14","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":27250,"unid":1001,"name":"侯钰相","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121481,"beginTime":"2016-11-21 20:53:56","endTime":"2016-11-21 21:09:26","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":25254,"unid":1001,"name":"张慧","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":0,"locPid":916,"locLon":104.191109,"locLan":30.82872,"locDesc":"博学楼","roomId":121397,"beginTime":"2016-11-21 20:46:13","endTime":"2016-11-21 21:06:02","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":28103,"unid":1001,"name":"罗瑶","icon":"http://imgs.gxapp.iydsj.com/imgs/06e15afe-5ddf-4cff-8ada-c8506c7deefe.jpeg","sex":0,"locPid":916,"locLon":104.191109,"locLan":30.82872,"locDesc":"博学楼","roomId":121411,"beginTime":"2016-11-21 20:47:27","endTime":"2016-11-21 21:05:53","totalNum":4,"currNum":4,"distance":2.0,"currUserEnter":false},{"uid":116363,"unid":1001,"name":"王政","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121339,"beginTime":"2016-11-21 20:38:46","endTime":"2016-11-21 20:59:05","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":68181,"unid":1001,"name":"邓力山","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":914,"locLon":104.191639,"locLan":30.830565,"locDesc":"体育馆","roomId":121376,"beginTime":"2016-11-21 20:43:14","endTime":"2016-11-21 20:56:49","totalNum":2,"currNum":1,"distance":2.0,"currUserEnter":false},{"uid":32121,"unid":1001,"name":"慕金林","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":914,"locLon":104.191639,"locLan":30.830565,"locDesc":"体育馆","roomId":121367,"beginTime":"2016-11-21 20:42:19","endTime":"2016-11-21 20:55:37","totalNum":6,"currNum":6,"distance":2.0,"currUserEnter":false},{"uid":27036,"unid":1001,"name":"苏明阳","icon":"http://imgs.gxapp.iydsj.com/imgs/f28eb2af-6123-43d1-8657-855b9b6f9987.jpeg","sex":1,"locPid":911,"locLon":104.193822,"locLan":30.83369,"locDesc":"学生公寓19栋","roomId":121354,"beginTime":"2016-11-21 20:40:41","endTime":"2016-11-21 20:52:44","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":23440,"unid":1001,"name":"徐彦钧","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121261,"beginTime":"2016-11-21 20:29:36","endTime":"2016-11-21 20:49:13","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":18401,"unid":1001,"name":"余文凯","icon":"http://imgs.gxapp.iydsj.com/imgs/014b857c-4540-4033-a832-e4cdb24f7ec2.jpg","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121223,"beginTime":"2016-11-21 20:25:44","endTime":"2016-11-21 20:49:06","totalNum":4,"currNum":4,"distance":2.0,"currUserEnter":false},{"uid":36043,"unid":1001,"name":"陈明月","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121239,"beginTime":"2016-11-21 20:27:49","endTime":"2016-11-21 20:45:27","totalNum":6,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":73185,"unid":1001,"name":"王熬","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121241,"beginTime":"2016-11-21 20:28:05","endTime":"2016-11-21 20:40:18","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":28091,"unid":1001,"name":"高启孟","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":916,"locLon":104.191109,"locLan":30.82872,"locDesc":"博学楼","roomId":121201,"beginTime":"2016-11-21 20:22:37","endTime":"2016-11-21 20:38:16","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":23090,"unid":1001,"name":"陈乾林","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":120997,"beginTime":"2016-11-21 19:54:36","endTime":"2016-11-21 20:36:31","totalNum":2,"currNum":2,"distance":5.0,"currUserEnter":false},{"uid":27541,"unid":1001,"name":"胡珈珲","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121161,"beginTime":"2016-11-21 20:16:41","endTime":"2016-11-21 20:36:12","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":16072,"unid":1001,"name":"饶再慧","icon":"http://imgs.gxapp.iydsj.com/imgs/851fba0e-3ead-43d9-984c-a68d707a75ca.jpeg","sex":0,"locPid":906,"locLon":104.192861,"locLan":30.836155,"locDesc":"飞翔路中段","roomId":121176,"beginTime":"2016-11-21 20:18:53","endTime":"2016-11-21 20:35:25","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":82685,"unid":1001,"name":"陈天宇","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":904,"locLon":104.195026,"locLan":30.837523,"locDesc":"学生公寓21栋","roomId":121150,"beginTime":"2016-11-21 20:16:14","endTime":"2016-11-21 20:33:13","totalNum":2,"currNum":2,"distance":2.0,"currUserEnter":false},{"uid":42864,"unid":1001,"name":"李生寿","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":121170,"beginTime":"2016-11-21 20:17:59","endTime":"2016-11-21 20:29:26","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":49881,"unid":1001,"name":"李云良","icon":"http://imgs.gxapp.iydsj.com/imgs/429df28f-3ed6-48e1-ac7d-fc7c6d67548c.jpg","sex":1,"locPid":909,"locLon":104.190193,"locLan":30.836414,"locDesc":"明理楼","roomId":121052,"beginTime":"2016-11-21 20:02:34","endTime":"2016-11-21 20:23:39","totalNum":4,"currNum":4,"distance":2.0,"currUserEnter":false},{"uid":32700,"unid":1001,"name":"杨荣贵","icon":"http://imgs.gxapp.iydsj.com/imgs/null","sex":1,"locPid":911,"locLon":104.193822,"locLan":30.83369,"locDesc":"学生公寓19栋","roomId":121036,"beginTime":"2016-11-21 20:00:28","endTime":"2016-11-21 20:14:08","totalNum":4,"currNum":3,"distance":2.0,"currUserEnter":false},{"uid":109272,"unid":1001,"name":"李壮","icon":"http://imgs.gxapp.iydsj.com/imgs/e2ae4dbc-d49d-46f4-8b88-21073f7b4c39.jpg","sex":1,"locPid":911,"locLon":104.193822,"locLan":30.83369,"locDesc":"学生公寓19栋","roomId":120926,"beginTime":"2016-11-21 19:41:53","endTime":"2016-11-21 20:03:03","totalNum":6,"currNum":5,"distance":2.0,"currUserEnter":false},{"uid":33540,"unid":1001,"name":"石玮","icon":"http://imgs.gxapp.iydsj.com/imgs/0aee4f22-a5d8-4c5e-971c-01e46ddae173.jpg","sex":1,"locPid":913,"locLon":104.192187,"locLan":30.832228,"locDesc":"1食堂","roomId":120951,"beginTime":"2016-11-21 19:45:20","endTime":"2016-11-21 20:01:40","totalNum":4,"currNum":4,"distance":2.0,"currUserEnter":false}]}
Updating 1 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 2 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 3 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 4 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 5 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 6 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 7 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 8 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 9 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 10 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 11 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 12 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 13 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 14 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 15 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 16 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 17 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 18 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 19 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 20 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 21 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 22 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 23 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 24 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 25 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 26 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 27 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 28 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 29 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 30 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 31 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 32 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 33 running groups data. 
{"fivePointJson":"[]","useZip":false}

Updating 34 running groups data. 
{"fivePointJson":"[]","useZip":false}

**Comment by beihaiguaishou** [comment]
@ftz8137 this are same problem as #8 ,the promble comes from you are not from SWJTU XIPU.There are many sollutions.If you use android and are rooted,I suggest you use root expolre and open /data/data/com.zjwh.android_wh_physicalfitness/databases/sport as sqlite and choose runpoint,and replace updateRoutes file's testPoints with it.The reason I suggest it is I think those points are more representative.You can also using [BaiduMap](http://api.map.baidu.com/lbsapi/getpoint/index.html) and pick as many as points,and replace.The best sollution I think is random pick point from route path,but It require change this script much.I hate foce running,so fuck it.

**Comment by Mud-Player** [comment]
@ZhouChaofan can you teach us to change this script?  I would like to learn.
thank you
